name: 🙋‍♂️ [Audioer] - 支持与反馈
description: "获取有关 Audioer、报告错误或请求功能的帮助。"
title: '🙋‍♂️ 支持与反馈: Audioer'
labels: ['support', 'feedback', 'question']
assignees:
  - jaywcjlove

body:
  - type: markdown
    attributes:
      value: |
        <img align="right" height="100" alt="Audioer" src="https://github.com/user-attachments/assets/7a836865-8c90-4119-87bc-19e06a76c957" /> 请尽可能详细地提供您的支持请求或反馈。

        Audioer 是一键将所有音频文件转换为 MP3 格式！支持多种音频格式之间的相互转换，操作简单，转换便捷。只需将文件拖入应用窗口，调整设置后点击按钮，即可轻松完成转换！

        支持转换的音频格式包括：`.aac`, `.ac3`, `.aifc`, `.aiff`, `.aif`, `.amr`, `.au`, `.caf`, `.dts`, `.eac3`, `.flac`, `.m4a`, `.mp2`, `.mp3`, `.mp4`, `.mka`, `.mov`, `.ogg`, `.opus`, `.ra`, `.rm`, `.spx`, `.tta`, `.voc`, `.vob`, `.wav`, `.webm`, `.wma`

        ### 联系信息

        如果您在使用我们的应用时遇到任何问题或需要支持，请随时通过以下方式与我们联系：

        - **电子邮件支持**: [kennyiseeyou@gmail.com](mailto:kennyiseeyou@gmail.com)
        - **社交媒体**: [Twitter](https://twitter.com/jaywcjlove)

        我们会尽快回复您的消息，感谢您对我们应用的支持！


  - type: textarea
    attributes:
      label: 🙋‍♂️ 您需要什么帮助？
      description: 描述您面临的问题或您想要请求的功能。
      placeholder: 例如，我遇到了问题...
    validations:
      required: true

  - type: dropdown
    id: os_version
    attributes:
      label: "💻 桌面"
      description: 您的操作系统和版本。
      options:
        - macOS 15.0 (Sequoia)
        - macOS 14.0 (Sonoma)
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **如何向我发送应用程序的崩溃报告？**

        - 在 macOS 上打开 Finder
        - 从“前往”菜单中选择 **前往文件夹…** <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>G</kbd>
        - 输入：**~/Library/Logs/DiagnosticReports**
        - 在出现的列表中，选择所有以应用程序名称开头的文件，将它们压缩成 ZIP 文件并发送给我
        - 将文件附加到此问题中

  - type: textarea
    attributes:
      label: ℹ️ 补充说明
      description: 在此添加有关问题的其他上下文信息。
      placeholder: 例如：截图、复现步骤等。
    validations:
      required: false